name: telegram-notifier-pull-request
on: pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Pull Request Status
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: |  #https://help.github.com/en/actions/reference/contexts-and-expression-syntax-for-github-actions#github-context
            ${{ github.event_name }} in ${{ github.repository }} by "${{ github.actor }}". ref[${{github.server_url}}/${{github.repository}}/pulls] 
